service: recipebook
image: ghcr.io/rixi0906/recipebook

servers:
  web:
    hosts:
      - 159.65.65.105
    # Usa --mount con Kamal: options.mounts
    options:
      mounts:
        - type=bind,source=/var/apps/recipe-book/log,target=/rails/log
        - type=bind,source=/var/apps/recipe-book/storage,target=/rails/storage
        - type=bind,source=/var/apps/recipe-book/tmp,target=/rails/tmp
        - type=bind,source=/var/apps/recipe-book/assets,target=/rails/public/assets
    env:
      clear:
        RAILS_ENV: production
        RACK_ENV: production
        RAILS_LOG_TO_STDOUT: "1"
        RAILS_SERVE_STATIC_FILES: "1"
        # Â¡OJO! Con accessory "db", usa su hostname "db"
        DATABASE_URL: "postgres://recipe_user:${POSTGRES_PASSWORD}@db:5432/recipebook_prod"
      secret:
        - RAILS_MASTER_KEY
        - POSTGRES_PASSWORD
        - GHCR_PAT

registry:
  server: ghcr.io
  username: rixi0906
  password:
    - GHCR_PAT

builder:
  arch: amd64
  dockerfile: Dockerfile
  args:
    RAILS_ENV: production

accessories:
  db:
    image: postgres:16
    host: 159.65.65.105
    env:
      clear:
        POSTGRES_DB: recipebook_prod
        POSTGRES_USER: recipe_user
      secret:
        - POSTGRES_PASSWORD
    options:
      volumes:
        - /var/apps/recipe-book/postgres:/var/lib/postgresql/data
